### ISSUE TITLE
Zillion todo list

### ISSUE THREAD

**Issue by bb111189** [Zilliqa/Zillion-issue#1]
Current TODO list for Zillion by Zilliqa team

- [ ] The Browser back button does not work.
- [ ] SSN Health bar
- [ ] Light mode
- [ ] Full historical transaction history
- [ ] Charts for statistical information
- [ ] Fix Complete withdrawal process 
- [ ] Fix APY calculation
- [ ] Optimize for mobile friendly

Current TODO list for Zillion suggested by Zilliqa community
- [ ] TBD

**Comment by Hongx01** [comment]
Suggest to add the tag "Available to stake" label or equivalent there.
![image](https://user-images.githubusercontent.com/43341181/93655821-49822f00-fa69-11ea-9bf0-031efa34d4a6.png)

**Comment by Hongx01** [comment]
50Zil stake successful but not shown in the dashboard. Gas fee lost.
[Bug1.docx](https://github.com/Zilliqa/Zillion-issue/files/5248921/Bug1.docx)

Expecting minimum of Zil required to stake is 100zil.

**Comment by kenostech** [comment]
[](url)
![Zil](https://user-images.githubusercontent.com/20414497/93694988-12705400-fb23-11ea-852e-dde600406a30.png)

UI Suggestion IMO:
1. Copy button should be herefor easier copying the address. Now, when we copy the address as shown on the image it includes the amount and network. It's a bit hazzle.

2. Zil address should be a little bit separeted from the amount.

3. Zil amount shoul have value indicator or should be in a different location not to confuse with Zil address.

Thank yuo.

**Comment by WuZenKey** [comment]
Thank you for Zillion, looks great and can't wait for main net launch.  Some possible improvements:

- Separate the "Hello Delegator! What Would You Like To Do Today?" from it's graphics box.  Put it as a rolling text or to the left or above the Delegation options - I passed right by it initially but it is a very appealing statement.

- When clicking Delegate Stake, the UI should list what ZIL is available.  Or, if it is partially staked, where it is in case you want to stake in a different pool.

- Under the graphics box "Staked Seed Nodes" have the top columns able to be sorted or filtered by either a search bar or by being able to click the column title such as "Name" or "Delegators" that way it can sort by high/low numbers or ABC making it easier to select a certain pool.

-  Recent Transactions on the very bottom should have it's own information graphic box on the very top next to Claim Rewards.  Even if it's a page skip to bottom of webpage, some users won't know to look past seeds.

If pictures can assist in any of this, I can quickly send.  

Thank you!

**Comment by 10131** [comment]
Great work ZIL Team! Can't wait to stake! A suggestion:

- Can we have a live staking calculator instead of the chart? Similar to this? https://www.stakingrewards.com/calculator

**Comment by georgeburduhos** [comment]
Website doesnt work when reload
https://www.dropbox.com/s/5c72h125kdvbbd3/Screenshot%202020-09-25%20at%2010.24.00.png?dl=0

I logged in through Zilpay - i made a delegation and i hit F5 - from that moment nothing showed

**Comment by jcyinnovations** [comment]
When attempting to transfer/withdraw stake, I'm requested to first claim any pending rewards. This is both inconvenient, and potentially a problem. With a large enough stake, I could potentially accumulate enough rewards while waiting for the withdrawal to complete.

I suggest that you automatically initiate the pending reward claim and the transfer/withdrawal request. Ideally, this can be done in a single transaction to avoid two confirm requests from the wallet.

Also, with any outstanding transactions, the UI should have a spinner popup/dialog with the transaction details. If there are multiple pending transactions, they should be shown in a list.
